### PR TITLE
switch back to regular platforms file for golden images

### PR DESCRIPTION
**Pull request by bryceml**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Don't we need all golden Images to reside on the new account before we can make the switch?

**Comment by bryceml** [comment]
> Don't we need all golden Images to reside on the new account before we can make the switch?

probably, I'm not aware of what status the golden images are in, I was hoping you knew.

**Comment by s0undt3ch** [comment]
No all have switched and we won't switch until we get out of the code freeze.

**Comment by bryceml** [comment]
This can be merged and the sodium file gotten rid of since we hard code ami-id's everywhere right?  the buildGoldenImages.groovy provides one based on the image it just built.

**Pull request merged**
